"""AiBot Initial revision 1

Revision ID: dd0b715c5a9f
Revises: 
Create Date: 2024-10-20 18:57:57.632753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd0b715c5a9f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='ai_bot'
    )
    op.create_table('img_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('value', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='ai_bot'
    )
    op.create_table('llm_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('value', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='ai_bot'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_tg', sa.BigInteger(), nullable=True),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('fullname', sa.String(length=64), nullable=True),
    sa.Column('fio', sa.String(length=256), nullable=True),
    sa.Column('phone_number', sa.String(length=320), nullable=True),
    sa.Column('encrypted_api_account_key', sa.LargeBinary(), nullable=True),
    sa.Column('date_reg', sa.DateTime(), nullable=True),
    sa.Column('id_topic_chat', sa.BigInteger(), nullable=True),
    sa.Column('access_flag', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='ai_bot'
    )
    op.create_table('model_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('name_role', sa.String(length=128), nullable=True),
    sa.Column('history_dialog', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['ai_bot.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='ai_bot'
    )
    op.create_table('temporary_dialog_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_tg', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('img_model_id', sa.Integer(), nullable=True),
    sa.Column('llm_model_id', sa.Integer(), nullable=True),
    sa.Column('quality_generated_image', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['img_model_id'], ['ai_bot.img_models.id'], ),
    sa.ForeignKeyConstraint(['llm_model_id'], ['ai_bot.llm_models.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['ai_bot.model_roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='ai_bot'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temporary_dialog_data', schema='ai_bot')
    op.drop_table('model_roles', schema='ai_bot')
    op.drop_table('users', schema='ai_bot')
    op.drop_table('llm_models', schema='ai_bot')
    op.drop_table('img_models', schema='ai_bot')
    op.drop_table('admin_group', schema='ai_bot')
    # ### end Alembic commands ###
